stages:
  - lint
  - test
  - deloy


variables:
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

test_stage:
  image: node:latest
  stage: lint
  script:
    - npm install eslint@7.32.0
    - node_modules/eslint/bin/eslint.js src/ 

deloy_swarm:
  image: alpine:3.11
  tags:
    - odin
  stage : deloy
  before_script:
  # Setup SSH deploy keys
    - "which ssh-agent || ( apk update && apk add openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $SSH_USERNAME_STAGING@$SSH_HOST_STAGING "mkdir -p ~/OdinOTAServer"
    - ssh $SSH_USERNAME_STAGING@$SSH_HOST_STAGING "cd ~/OdinOTAServer/web && rm -rf .git "
    - rm -rf $(pwd)/.git 
    - scp -p -r $(pwd)/src $(pwd)/package.json $(pwd)/public $SSH_USERNAME_STAGING@$SSH_HOST_STAGING:~/OdinOTAServer/web/
    - ssh $SSH_USERNAME_STAGING@$SSH_HOST_STAGING "cd ~/OdinOTAServer/web && docker build . -t odin_ota_web && docker stop odin_ota_web && docker rm odin_ota_web && docker run -d --name odin_ota_web -p 8082:80 odin_ota_web && exit"
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /-beta$/

deloy_stage:
  image: alpine:3.11
  tags:
    - odin
  stage : deloy
  before_script:
  # Setup SSH deploy keys
    - "which ssh-agent || ( apk update && apk add openssh-client )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh $SSH_USERNAME_STAGING@$SSH_HOST_STAGING "mkdir -p ~/OdinOTAServer"
    - ssh $SSH_USERNAME_STAGING@$SSH_HOST_STAGING "cd ~/OdinOTAServer/web2 && rm -rf .git "
    - rm -rf $(pwd)/.git 
    - scp -p -r $(pwd)/src $(pwd)/package.json $SSH_USERNAME_STAGING@$SSH_HOST_STAGING:~/OdinOTAServer/web2/
    - ssh $SSH_USERNAME_STAGING@$SSH_HOST_STAGING " cd ~/OdinOTAServer/web2 && docker build . -t odin_ota_web2 && docker stop odin_ota_web2 && docker rm odin_ota_web2 && docker run -d --name odin_ota_web2 -p 8083:80 odin_ota_web2 && exit"
  only:
    - master
